################################################################################
#
# libwebsockets-custom
# replecement for libwebsockets
#
################################################################################

LIBWEBSOCKETS_CUSTOM_VERSION = 4.2.1
LIBWEBSOCKETS_CUSTOM_SOURCE = libwebsockets-$(LIBWEBSOCKETS_CUSTOM_VERSION).tar.gz
LIBWEBSOCKETS_CUSTOM_SITE = $(call github,warmcat,libwebsockets,v$(LIBWEBSOCKETS_CUSTOM_VERSION))
LIBWEBSOCKETS_CUSTOM_LICENSE = MIT with exceptions
LIBWEBSOCKETS_CUSTOM_LICENSE_FILES = LICENSE
LIBWEBSOCKETS_CUSTOM_DEPENDENCIES = zlib libuv-custom
LIBWEBSOCKETS_CUSTOM_INSTALL_STAGING = YES
LIBWEBSOCKETS_CUSTOM_CONF_OPTS = \
	-DLWS_WITHOUT_TESTAPPS=ON \
	-DLWS_IPV6=ON \
	-DLWS_UNIX_SOCK=ON \
	-DLWS_WITHOUT_EXTENSIONS=OFF

# If LWS_MAX_SMP=1, then there is no code related to pthreads compiled
# in the library. If unset, LWS_MAX_SMP defaults to 32 and a small
# amount of pthread mutex code is built into the library.
ifeq ($(BR2_TOOLCHAIN_HAS_THREADS),)
LIBWEBSOCKETS_CUSTOM_CONF_OPTS += -DLWS_MAX_SMP=1
else
LIBWEBSOCKETS_CUSTOM_CONF_OPTS += -DLWS_MAX_SMP=
endif

# TODO LWS_WITH_MBEDTLS

ifeq ($(BR2_PACKAGE_OPENSSL),y)
LIBWEBSOCKETS_CUSTOM_DEPENDENCIES += openssl host-openssl
LIBWEBSOCKETS_CUSTOM_CONF_OPTS += -DLWS_WITH_SSL=ON
else
LIBWEBSOCKETS_CUSTOM_CONF_OPTS += -DLWS_WITH_SSL=OFF
endif

ifeq ($(BR2_PACKAGE_LIBGLIB2),y)
LIBWEBSOCKETS_CUSTOM_DEPENDENCIES += libglib2
LIBWEBSOCKETS_CUSTOM_CONF_OPTS += -DLWS_WITH_GLIB=ON
else
LIBWEBSOCKETS_CUSTOM_CONF_OPTS += -DLWS_WITH_GLIB=OFF
endif

ifeq ($(BR2_PACKAGE_UTIL_LINUX_LIBMOUNT),y)
LIBWEBSOCKETS_CUSTOM_DEPENDENCIES += util-linux
LIBWEBSOCKETS_CUSTOM_CONF_OPTS += -DLWS_WITH_FSMOUNT=ON
else
LIBWEBSOCKETS_CUSTOM_CONF_OPTS += -DLWS_WITH_FSMOUNT=OFF
endif

#ifeq ($(BR2_PACKAGE_LIBUV),y)
#LIBWEBSOCKETS_CUSTOM_DEPENDENCIES += libuv
#LIBWEBSOCKETS_CUSTOM_CONF_OPTS += -DLWS_WITH_LIBUV=ON
#else
#LIBWEBSOCKETS_CUSTOM_CONF_OPTS += -DLWS_WITH_LIBUV=OFF
#endif

# Always build with libuv
LIBWEBSOCKETS_CUSTOM_CONF_OPTS += -DLWS_WITH_LIBUV=ON

ifeq ($(BR2_SHARED_LIBS),y)
LIBWEBSOCKETS_CUSTOM_CONF_OPTS += -DLWS_WITH_STATIC=OFF
endif

$(eval $(cmake-package))
